version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    working_dir: /app/backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: my-app/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db